export default [
  'Administrador',
  'Advogado',
  'Aeronauta',
  'Arquivista / Técnico de Arquivo',
  'Artista',
  'Assistente Social',
  'Atleta Profissional de Futebol',
  'Atuário',
  'Bibliotecário',
  'Biomédico',
  'Biólogo',
  'Bombeiro Civil',
  'Comerciário',
  'Contabilista',
  'Corretor de Imóveis',
  'Corretor de Seguros',
  'Despachante Aduaneiro',
  'Engenheiro/ Arquiteto/ Agrônomo',
  'Economista Doméstico',
  'Economista',
  'Educação Física',
  'Empregado Doméstico',
  'Enfermagem',
  'Enólogo',
  'Engenharia de Segurança',
  'Estatástico',
  'Estudante',
  'Fisioterapeuta e Terapeuta Ocupacional',
  'Farmacêutico',
  'Fonoaudiólogo',
  'Garimpeiro',
  'Geógrafo',
  'Geólogo',
  'Guardador e Lavador de Veículos',
  'Instrutor de Trânsito',
  'Jornalista',
  'Leiloeiro',
  'Leiloeiro Rural',
  'Massagista',
  'Médico',
  'Medicina Veterinária',
  'Mototaxista e Motoboy',
  'Museólogo',
  'Músico',
  'Nutricionista',
  'Oceanógrafo',
  'Odontologia',
  'Orientador Educacional',
  'Peção de Rodeio',
  'Pescador Profissional',
  'Psicologia',
  'Publicitário',
  'Químico',
  'Radialista',
  'Relações Públicas',
  'Representantes Comerciais Autônomos',
  'Repentista',
  'Secretário ',
  'Sociólogo',
  'Taxista',
  'Tradutor e Intérprete ',
  'Técnico em Administração',
  'Técnico Industrial',
  'Técnico em Prótese Dentária',
  'Técnico em Radiologia',
  'Turismólogo',
  'Zootecnista',
].map((x) => {
  return {
    id: x,
    title: x,
  };
});
